### ISSUE TITLE
Implement github actions

### ISSUE THREAD

**Issue by alexrecuenco** [alexrecuenco/Notes_Master_UCM_Tech_Fotonica#1]
See https://stackoverflow.com/a/63822945.

It recommends either some [config](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore)

```
on:
  push:
    paths:
      - folder1/**
```

Or [paths-filter](https://github.com/dorny/paths-filter)
